CREATE TABLE dbo.BouncedEmails
(
	Id					INT IDENTITY (1, 1) PRIMARY KEY,
	ExternalId			INT NOT NULL,
	CampaignId			INT NOT NULL,
	ContactEmail		VARCHAR(255) NOT NULL,
	BounceDate			DATETIME2 NOT NULL,
	BounceReason		VARCHAR(255) NOT NULL,
	BounceType			VARCHAR(255) NOT NULL,
	ResponseText		VARCHAR(MAX) NOT NULL
) ON [PRIMARY]
GO