CREATE TABLE import.Campaigns (
    ID INT NOT NULL,
    SubaccountID INT NULL,
    Name NVARCHAR(255) NULL,
    CampaignTypeID INT NULL,
    Type NVARCHAR(100) NULL,
    CreatedBy NVARCHAR(255) NULL,
    CreatedByUserID INT NULL,
    CreatedDate DATETIME2(3) NULL,
    ModifiedBy NVARCHAR(255) NULL,
    ModifiedByUserID INT NULL,
    ModifiedDate DATETIME2(3) NULL,
    DeletedDate DATETIME2(3) NULL,
    ReportDeletedDate DATETIME2(3) NULL,
    IsSetup BIT NULL,
    Status NVARCHAR(50) NULL,
    FirstSendDate DATETIME2(3) NULL,
    LastSendDate DATETIME2(3) NULL,
    TotalSent INT NULL,
    CanBeModified BIT NULL,
    CanBeReported BIT NULL,
    SendDate DATETIME2(3) NULL,
    FromEmail NVARCHAR(320) NULL,
    FromName NVARCHAR(255) NULL,
    ReplyEmail NVARCHAR(320) NULL,
    SubjectLine NVARCHAR(500) NULL,
    CONSTRAINT PK_Campaigns PRIMARY KEY (ID)
);
GO
