CREATE TABLE import.Contacts (
    ID INT NOT NULL,
    SubaccountID INT NULL,
    SalesforceContactID NVARCHAR(100) NULL,
    SalesforceLeadID NVARCHAR(100) NULL,
    MicrosoftDynamicsContactID NVARCHAR(100) NULL,
    MicrosoftDynamicsLeadID NVARCHAR(100) NULL,
    SourceID INT NULL,
    EmailFormat NVARCHAR(20) NULL,
    EmailFormatID INT NULL,
    Email NVARCHAR(320) NULL,
    EmailStatusID INT NULL,
    MobileStatusID INT NULL,
    MobileNumber NVARCHAR(50) NULL,
    MobileRegion INT NULL,
    Salutation NVARCHAR(50) NULL,
    Firstname NVARCHAR(150) NULL,
    Lastname NVARCHAR(150) NULL,
    Telephone NVARCHAR(50) NULL,
    URN NVARCHAR(100) NULL,
    Company NVARCHAR(255) NULL,
    CreatedDate DATETIME2(3) NULL,
    CreatedFromSourceID NVARCHAR(50) NULL,
    ModifiedDate DATETIME2(3) NULL,
    ModifiedFromSourceID NVARCHAR(50) NULL,
    EmailUnsubscribedDate DATETIME2(3) NULL,
    EmailUnsubscribedFromSourceID NVARCHAR(50) NULL,
    SmsUnsubscribedDate DATETIME2(3) NULL,
    SmsUnsubscribedFromSourceID NVARCHAR(50) NULL,
    EmailHardBounceDate DATETIME2(3) NULL,
    DoubleOptInConfirmationDate DATETIME2(3) NULL,
    InleadsScore INT NULL,
    CustomerAccountID INT NULL,
    EmailEngagementStatus INT NULL,
    HardBouncedDate DATETIME2(3) NULL,
    LastSoftBouncedDate DATETIME2(3) NULL,
    LastSentDate DATETIME2(3) NULL,
    LastDisplayedDate DATETIME2(3) NULL,
    LastClickedDate DATETIME2(3) NULL,
    FirstInleadsVisitDate DATETIME2(3) NULL,
    LastInleadsVisitDate DATETIME2(3) NULL,
    IncludeInUR BIT NULL,
    CONSTRAINT PK_Contacts PRIMARY KEY (ID)
);
GO